services:
  app:
    build:
      context: ../
      dockerfile: config/Dockerfile
    container_name: medical-app
    env_file:
      - app.env
    expose:
      - "5000"

networks:
  deploy_net:
    external: true
